server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: WingLing_Studio@163.com
    password: MOWZCGWVBHNDKXQP
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #465??994
    properties.mail.display.sendmail: WingLing_Studio@163.com
    properties.mail.display.sendname: ???????
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: WingLing_Studio@163.com
  datasource:
    url: jdbc:mysql://localhost:3306/lab_reservation_system
    password: abc123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

prop:
  upload-folder: E:/test/

